Skiddle refactor
jonquil-NC/make-my-day-api pull request #4
Opened 2024-09-30 09:47 UTC by fabiopulvirenti

- retrieve data from skiddle api
- create server to expose them
- populate the database h2

2024-09-30 09:59 UTC, ag-af requested changes

2024-09-30 09:59 UTC, ag-af commented on src/main/java/com/northcoders/makemydayapi/controller/SkiddedController.java
> +public class SkiddedController {
Typo in class name (Skidded instead of Skiddle)

2024-09-30 09:59 UTC, ag-af commented on src/main/java/com/northcoders/makemydayapi/controller/UserController.java
> +    public ResponseEntity<String> signup(@RequestBody User user) {
Typo (maybe uppercase for signup ("signUp")

2024-09-30 10:14 UTC, ag-af reviewed
Great work!

2024-09-30 10:14 UTC, ag-af approved these changes

2024-09-30 17:14 UTC, chatonode commented
Thanks to @fabiopulvirenti 's work during weekend, we just "copy/paste"d much of his code across different files and places. As a result, most of our commits involve refactoring.

We also changed the shape of `Activity` and `Location` model entity classes.

2024-09-30 18:19 UTC, chatonode commented
- I removed all user/scheduler/repository files. They seem like beyond the scope of this branch.
- I also moved `API_KEY` to somewhere secure, within the help of [`@Value`](https://www.baeldung.com/spring-value-annotation) annotation.

2024-10-01 11:01 UTC, daitamer reviewed
looks neat and makes sense

2024-10-01 12:03 UTC, chatonode commented
Tried to exclude some of the files to make it as same as they are in `main` branch. But, GitHub sees two identical files as different.

So, I aimed fixing this issue in my previous commits, nothing to review for you guys @daitamer @ag-af . Thank you so much for previous reviews.

---

I am merging this one into our `main` branch with **these affected files**:

- 4 new annotations on models of
  - `Activity` and
  - `Location`
- 9 new `ActivityType` enum values
- `spring.profiles.active=dev` as an extra line in `application.properties`

2024-10-01 13:19 UTC, merged